'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WheelOfFortune.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property bankrupt() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("bankrupt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BlueArrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlueArrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Bonus_Wheel_Music() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Bonus_Wheel_Music", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BonusWheel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BonusWheel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Buzzer() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Buzzer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CategoryBar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CategoryBar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Choose_letters() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Choose_letters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property clock() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("clock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property clock_new() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("clock_new", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CLUE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLUE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CurrentPlayerLeftSide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CurrentPlayerLeftSide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CurrentPlayerRightSide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CurrentPlayerRightSide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ding() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property double_buzz() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("double_buzz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DownChevron() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DownChevron", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property editOptions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("editOptions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Express() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Express", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExpressLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExpressLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property finalspin() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("finalspin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FinalSpinAnimation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FinalSpinAnimation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FreePlay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FreePlay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gift_Tag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gift_Tag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property gotham_bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("gotham_bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Gotham_Book_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Gotham_Book_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Half_Car() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Half_Car", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property halfcar() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("halfcar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property helvetica_condensed_black_se() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("helvetica_condensed_black_se", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MDW_Back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MDW_Back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MDW_Front() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MDW_Front", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property music_bonus_win_vamp_intro() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("music_bonus_win_vamp_intro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mystery_10000_2014() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mystery_10000_2014", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mystery_2014() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mystery_2014", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mystery_2014_Bankrupt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mystery_2014_Bankrupt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NameTag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NameTag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nomorevowels() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nomorevowels", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Prize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Prize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property prize_puzzle_reveal() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("prize_puzzle_reveal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property puzzle_reveal() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("puzzle_reveal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property puzzle_solved() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("puzzle_solved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property puzzle_solved_new() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("puzzle_solved_new", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property R_S_T_L_N_E() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("R_S_T_L_N_E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screenshot__190_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screenshot (190)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property snd_express() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("snd_express", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property snd_fireworks() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("snd_fireworks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property snd_mystery_wedge() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("snd_mystery_wedge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property snd_no_more_vowels() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("snd_no_more_vowels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property snd_vowels_only() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("snd_vowels_only", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Speedup() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Speedup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property toss_up() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("toss_up", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Toss_Up_1000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Toss_Up_1000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Toss_Up_2000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Toss_Up_2000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Toss_Up_3000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Toss_Up_3000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property toss_up_new() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("toss_up_new", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property toss_up_reveal() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("toss_up_reveal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property toss_win_eq() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("toss_win_eq", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property toss_win_eq_new() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("toss_win_eq_new", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Wheel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wheel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property wheel_spin() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("wheel_spin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelBoard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelBoard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelBonusBeforeReveal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelBonusBeforeReveal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelBonusChooseLetters() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelBonusChooseLetters", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelBonusPrizeReveal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelBonusPrizeReveal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelBonusRSTLNE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelBonusRSTLNE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelCover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelCover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wheelCoverHD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wheelCoverHD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wheelCoverHDBonus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wheelCoverHDBonus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wheelCoverHDR2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wheelCoverHDR2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wheelCoverHDR3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wheelCoverHDR3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wheelCoverHDR4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wheelCoverHDR4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelCustomizerPackSelect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelCustomizerPackSelect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelCustomizerScreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelCustomizerScreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelLetterReveal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelLetterReveal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelMainMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelMainMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelNameCustomizer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelNameCustomizer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelPackSelect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelPackSelect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelPuzzleBoard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelPuzzleBoard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelSonyTVCity() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelSonyTVCity", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property wheelspinlong() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("wheelspinlong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelSpinMeter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelSpinMeter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelTilted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelTilted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelTiltedSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelTiltedSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelTiltedSmallBonus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelTiltedSmallBonus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelTiltedSmallBonusCards() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelTiltedSmallBonusCards", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelTiltedSmallR2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelTiltedSmallR2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelTiltedSmallR3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelTiltedSmallR3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelTiltedSmallR4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelTiltedSmallR4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WheelTossUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WheelTossUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Wild_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wild_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wof() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wof", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WOF_100_000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WOF_100_000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WOF_34_000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WOF_34_000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WOF_35_000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WOF_35_000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WOF_40_000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WOF_40_000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WOF_45_000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WOF_45_000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WOF_50_000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WOF_50_000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WOF_CAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WOF_CAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property wof_chant() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("wof_chant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wof_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wof-logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WOF_One_Million_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WOF_One_Million_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WOF_RearFolded() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WOF_RearFolded", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wof_twitter_skin_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wof_twitter_skin_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
